# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-CMD-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

#permissions:
#  contents: read

jobs:
  R-CMD-check:
    name: R CMD check on R version ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        r-version: ['3.6.3', 'release', 'devel']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
          
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
          remotes::install_github("SamCH93/ciCalibrate")
        shell: Rscript {0}
        
      - name: Check
        run: rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran") error_on = "warning")
        shell: Rscript {0}
